### ISSUE TITLE
Interfering with Passwords app

### ISSUE THREAD

**Issue by joshp23** [pulsejet/nextcloud-oidc-login#8] opened 2019-11-17 18:34 UTC
With this app enabled, the passwords app gives the following errors when attempting to go to the app page:
```
{"reqId":"mYaljADDTD7RuA1bQX9G","level":2,"time":"2019-11-16T23:29:29+00:00","remoteAddr":"00.00.00.000","user":"NAME","app":"passwords","method":"GET","url":"\/apps\/passwords\/","message":"Cancelled expired session cfe65ee5-8fb3-428b-bd98-8d33e1faa9a9 for NAME","userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:70.0) Gecko\/20100101 Firefox\/70.0","version":"17.0.1.1"}
{"reqId":"mYaljADDTD7RuA1bQX9G","level":3,"time":"2019-11-16T23:29:29+00:00","remoteAddr":"00.00.00.000","user":"NAME","app":"passwords","method":"GET","url":"\/apps\/passwords\/","message":{"Exception":"OC\\Authentication\\Exceptions\\PasswordlessTokenException","Message":"","Code":0,"Trace":[{"file":"\/var\/www\/nextcloud\/lib\/private\/Authentication\/Token\/Manager.php","line":181,"function":"getPassword","class":"OC\\Authentication\\Token\\PublicKeyTokenProvider","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"\/var\/www\/nextcloud\/apps\/passwords\/lib\/Helper\/Token\/ApiTokenHelper.php","line":220,"function":"getPassword","class":"OC\\Authentication\\Token\\Manager","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"\/var\/www\/nextcloud\/apps\/passwords\/lib\/Helper\/Token\/ApiTokenHelper.php","line":125,"function":"getUserPassword","class":"OCA\\Passwords\\Helper\\Token\\ApiTokenHelper","type":"->","args":[]},{"file":"\/var\/www\/nextcloud\/apps\/passwords\/lib\/Helper\/Token\/ApiTokenHelper.php","line":204,"function":"createToken","class":"OCA\\Passwords\\Helper\\Token\\ApiTokenHelper","type":"->","args":["Passwords Session 16.11.19 23:29 - NAME@00.00.00.000"]},{"file":"\/var\/www\/nextcloud\/apps\/passwords\/lib\/Helper\/Token\/ApiTokenHelper.php","line":107,"function":"createWebUiToken","class":"OCA\\Passwords\\Helper\\Token\\ApiTokenHelper","type":"->","args":[]},{"file":"\/var\/www\/nextcloud\/apps\/passwords\/lib\/Controller\/PageController.php","line":142,"function":"getWebUiToken","class":"OCA\\Passwords\\Helper\\Token\\ApiTokenHelper","type":"->","args":[]},{"file":"\/var\/www\/nextcloud\/apps\/passwords\/lib\/Controller\/PageController.php","line":108,"function":"addHeaders","class":"OCA\\Passwords\\Controller\\PageController","type":"->","args":[]},{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":170,"function":"index","class":"OCA\\Passwords\\Controller\\PageController","type":"->","args":[]},{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":99,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Passwords\\Controller\\PageController"},"index"]},{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/App.php","line":126,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Passwords\\Controller\\PageController"},"index"]},{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Passwords\\Controller\\PageController","index",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"passwords.page.index"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"_route":"passwords.page.index"}]},{"file":"\/var\/www\/nextcloud\/lib\/private\/Route\/Router.php","line":297,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"_route":"passwords.page.index"}]},{"file":"\/var\/www\/nextcloud\/lib\/base.php","line":1000,"function":"match","class":"OC\\Route\\Router","type":"->","args":["\/apps\/passwords\/"]},{"file":"\/var\/www\/nextcloud\/index.php","line":42,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"\/var\/www\/nextcloud\/lib\/private\/Authentication\/Token\/PublicKeyTokenProvider.php","Line":190,"CustomMessage":"--"},"userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:70.0) Gecko\/20100101 Firefox\/70.0","version":"17.0.1.1"}
```
When this app is disabled, passwords app works.

**Comment by pulsejet** [comment] 2019-11-17 18:44
Not sure this can be worked around, since it is throwing a `PasswordlessTokenException`. One potential way might be to set the user's password to something else before login, but this will make it impossible to use password login.

**Comment by Excel1** [comment] 2020-05-04 12:04
https://github.com/marius-wieschollek/passwords/issues/267

**Comment by marius-wieschollek** [comment] 2020-05-07 19:15
The `PasswordlessTokenException` is actually not the reason why the app does not work. The app can generate a token just fine without the password. (At least in the current version 2020.5.0)

What seems to be the issue is that the app uses the `@CORS` annotation for any api controller endpoint. If you look at the Nextcloud [CORS Middleware](https://github.com/nextcloud/server/blob/master/lib/private/AppFramework/Middleware/Security/CORSMiddleware.php#L91), you see that it actually logs the user out, and then back in with the data from the HTTP-Authorization header.

That triggers the postLogout hook of oidc_login and the request is terminated and redirected to the logout page (See [here](https://github.com/pulsejet/nextcloud-oidc-login/blob/master/lib/AppInfo/Application.php#L63)). I have also confirmed that the same issue happens with the News app if you try to use the News Android App.

I can't fix this in my app, but maybe it is possible to detect if the hook was called from the CORSMiddleware.

**Comment by pulsejet** [comment] 2020-05-08 13:17
Wow never saw this coming. Since everything is happening in a single request, it should technically be possible to check if it is a CORS request. Will try to find a way around this, though maybe this is something that needs fixing upstream ...

**Comment by Excel1** [comment] 2020-05-08 14:01
@pulsejet this will be great. The Passwords Web Extension is also not working cause this error.

**Comment by pulsejet** [comment] 2020-05-08 17:41
This should be fixed in v1.3.1. Can someone confirm this so this can be closed?

**Comment by Excel1** [comment] 2020-05-09 15:15
@pulsejet i will test it,as soon as i can with the group feature.

**Comment by joshp23** [comment] 2020-05-14 22:27
@pulsejet Seems to be working

**Comment by pulsejet** [comment] 2020-05-15 07:27
Awesome thanks!

**Closed by pulsejet** 2020-05-15 07:27 UTC
Labels: bug

**Comment by craig0990** [comment] 2020-05-17 15:28
Just logging in (at midnight) to say "thanks" 🙏🏻😅

This update instantly fixed Notes, Deck, and News for me. I've previously been getting "Your server did respond with HTTP 302" or something like that across all apps, but this update fixed everything

**Comment by pulsejet** [comment] 2020-05-17 17:02
Awesome! All thanks to @marius-wieschollek for figuring this out =D
