### ISSUE TITLE
Skeleton files not copied 

### ISSUE THREAD

**Issue by stephanieminder973** [pulsejet/nextcloud-oidc-login#211] opened 2022-12-20 12:05 UTC
Hi there,

I use this app to connect Nextcloud with OpenId connect but when the user's count is created, the files in the skeleton folder are not copied.

versions : 
OpenID Connect Login : 2.4.0
Nextcloud : 24.0.7

Thanks for your help.

**Comment by azmeuk** [comment] 2023-01-13 14:09
Closing as a duplicate of #144

**Closed by azmeuk** 2023-01-13 14:09 UTC
